### ISSUE TITLE
Error: COMPLETED release must not have fraction

### ISSUE THREAD

**Issue by rokasAt10speed** [joutvhu/publish-android#2]
<img width="637" alt="SCR-20230203-gp2" src="https://user-images.githubusercontent.com/114087573/216571376-ca9e51c8-f2ce-4232-9df5-2bd46dce7659.png">

Cannot upload the app with `userFraction: 1.0` (which is the default setting)

**Comment by joutvhu** [comment]
The issue has been fixed by version v1.0.1
